# Generated by Django 6.0.1 on 2026-01-28 11:42

import apps.workshop.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد کارگاه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارگاه')),
                ('main_image', models.ImageField(upload_to=apps.workshop.models.workshop_image_path, verbose_name='تصویر اصلی')),
                ('date_event', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان برگزاری ')),
                ('location', models.CharField(max_length=200, verbose_name='مکان برگزاری')),
                ('teacher', models.CharField(max_length=200, verbose_name='مدرس')),
                ('description', models.TextField(verbose_name='اطلاعات کارگاه ')),
                ('register_way', models.TextField(verbose_name='نحوه ثبت نام')),
                ('report_text', models.TextField(default='null', null=True, verbose_name='متن گزارش کارگاه ')),
                ('num_of_visit', models.IntegerField(default=0, verbose_name='تعداد بازدید از گزارش')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال / غیر فعال')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='WorkshopStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد وضعیت کارگاه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کارگاه')),
            ],
            options={
                'verbose_name': 'کارگاه',
                'verbose_name_plural': 'کارگاهها',
                'db_table': 't_Workshop_Status',
            },
        ),
        migrations.CreateModel(
            name='WorkshopGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد تصویر')),
                ('name', models.CharField(max_length=100, verbose_name='نام تصویر')),
                ('imae', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='کارگاه'), verbose_name='تصویر')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop', verbose_name='کارگاه')),
            ],
            options={
                'verbose_name': 'تصویر کارگاه',
                'verbose_name_plural': 'تصاویر کارگاه ',
                'db_table': 't_WorkshopGallery',
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_statue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workshopstatus', verbose_name='وضعیت کارگاه'),
        ),
    ]
