# Generated by Django 5.2.8 on 2025-12-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاک', 'verbose_name_plural': 'وبلاگ ها'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='t_blog',
        ),
    ]
