# Generated by Django 5.2.8 on 2025-11-24 20:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('description', models.TextField(default='description', verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/places/', verbose_name='تصویر')),
                ('visiting_day', models.CharField(max_length=100, verbose_name='روزهای بازدید')),
                ('visiting_hour', models.CharField(max_length=100, verbose_name='ساعت بازدید')),
                ('ruls', models.TextField(verbose_name='قوانین')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ثبت')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
                'db_table': 't_Places',
            },
        ),
        migrations.CreateModel(
            name='VisitorsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': ' بازدید کننده',
                'verbose_name_plural': 'بازدید کنندگان',
                'db_table': 't_visitors_type',
            },
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='بهای بلیط')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='مکان')),
                ('visitor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.visitorstype', verbose_name='گروه بازدید')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
                'db_table': 't_ticket_price',
            },
        ),
    ]
