# Generated by Django 6.0.1 on 2026-01-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetous',
            old_name='message',
            new_name='mesage',
        ),
        migrations.RemoveField(
            model_name='messagetous',
            name='age',
        ),
        migrations.AlterModelTable(
            name='messagetous',
            table='t_mesage',
        ),
    ]
