# Generated by Django 5.2.8 on 2025-12-10 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('description', models.TextField(verbose_name='متن مقاله')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت ')),
                ('main_image', models.ImageField(upload_to='images/blog', verbose_name='تصویر اصلی ')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
        ),
    ]
