# Generated by Django 5.2.8 on 2026-01-15 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=255, verbose_name='عنوان پیام')),
                ('message', models.TextField(verbose_name='منت پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='دیده شده توسط مدیر')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیامها',
                'db_table': 't_messages',
            },
        ),
    ]
