# Generated by Django 5.2.8 on 2025-12-29 20:19

import apps.Article.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_blog_options_alter_blog_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد مقاله')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('main_image', models.ImageField(upload_to=apps.Article.models.article_image_path, verbose_name='تصویر اصلی ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='متن کوتاه')),
                ('abstract', models.TextField(verbose_name='چکیده مقاله')),
                ('keywords', models.CharField(max_length=100, verbose_name='کلمات کلیدی')),
                ('pdf_name', models.CharField(max_length=100, verbose_name='نام فایل اصلی مقاله')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('number_of_visit', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال ')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 't_Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد تصویر')),
                ('name', models.CharField(max_length=100, verbose_name='نام نصویر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'db_table': 't_ArticleGallery',
            },
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد گروه')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
                'db_table': 't_ArticleGroup',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='کد نویسنده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('education', models.CharField(max_length=100, verbose_name='تحصیلات')),
                ('job_title', models.CharField(max_length=100, verbose_name='شغل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'db_table': 't_Author',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='article',
            name='article_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articlegroup', verbose_name='گروه مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.author', verbose_name='نویسنده'),
        ),
    ]
