# Generated by Django 5.2.8 on 2026-01-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
