# Generated by Django 6.0.1 on 2026-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlegallery',
            options={'verbose_name': ' مقاله تصویر', 'verbose_name_plural': 'تصاویر مقالات'},
        ),
        migrations.AlterField(
            model_name='articlegallery',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام تصویر'),
        ),
    ]
