# Generated by Django 5.2.8 on 2025-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_article_articlegallery_articlegroup_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlegroup',
            options={'verbose_name': ' گروه مقاله', 'verbose_name_plural': 'گروه مقالات'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='articles', to='blog.author', verbose_name='نویسنده'),
        ),
    ]
